### PR TITLE
make tests cross-platform

### PR DESCRIPTION
**Pull request by Lacrymology**
use the `path/filepath` package to make tests work cross-platform

### CODE REVIEW

**Comment by EvanStanford** [comment]
Thanks for this improvement! Worked for me.

**Comment by Lacrymology** [comment]
I have  a question: how do you use this? because I had to create a `main` package, and export a `cams.MakeCoordinate` constructor function

**Comment by Lacrymology** [comment]
https://github.com/Lacrymology/make-stls/blob/master/make-stls.go
https://github.com/Lacrymology/cams/blob/master/cams.go#L16

**Comment by EvanStanford** [comment]
My original plan was that this would be a package used in a program with UI. Since I probably won't get around to doing that I should add the main you wrote. I have been using it via a worse main program I wrote.

**Comment by EvanStanford** [comment]
Ok, I added a main. Thanks for the input, I am new at Go.

**Comment by Lacrymology** [comment]
np, glad it was useful

**Pull request merged**
